### ISSUE TITLE
💡 [GSSOC'23] - Patient prescription

### ISSUE THREAD

**Issue by vivxsdb** [Anmol-Baranwal/WaitSmart#24]
### Concise Description

patient past prescription help doctor to better understand their medications

### About Feature

Actually I want to add a feature of patient prescription where the user can access their past prescriptions. Can u please assgin me this issue under GSSOC'23

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects/blob/main/CONTRIBUTING.md) of this project.

**Comment by Anmol-Baranwal** [comment]
@vivxsdb
This repository is not under GSSoC'23.

> This is my personal project. If you still want to contribute, let me know.

**Comment by vivxsdb** [comment]
I thought it was gssoc

**Comment by Anmol-Baranwal** [comment]
> I thought it was gssoc

No worries, I am closing the issue. You can re-open it if you want to work on this later.
